name: Обновление RSS новостей

on:
  schedule:
    - cron: '0 7 * * *'  # каждый день в 7:00 утра UTC (~10:00 по Москве)
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Клонировать репозиторий
        uses: actions/checkout@v3

      - name: Установить дату
        run: echo "Обновление: $(date)" >> update-log.txt

      - name: Коммит и пуш
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add update-log.txt
          git commit -m "Ежедневное обновление: $(date)"
          git push
